version: '3'

services:
  drupal:
    image: custom-drupal
    build: .
    ports:
      - 8080:80
    volumes:
    - drupal-modules:/var/www/html/modules
    - drupal-profiles:/var/www/html/profiles
    - drupal-themes:/var/www/html/themes
    - drupal-sites:/var/www/html/sites
    restart: always

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: hello
    volumes:
    - drupal-data:/var/lib/postgresql/data
    restart: always

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
