version: '3'

services:
  drupal:
    image: drupal:8.5-rc
    ports:
      - 8080:80
    volumes:
    - /var/www/html/modules
    - /var/www/html/profiles
    - /var/www/html/themes
    - /var/www/html/sites
    restart: always

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: hello
    restart: always
